name: Output Scheduled Actions
description: ""

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      with:
        script: |
          const { GITHUB_ACTION_PATH } = process.env;
          const script = require(`${GITHUB_ACTION_PATH}/dist/index.js`);

          const scriptInputs = {
            token: "${{ inputs.token }}",
            repo: "${{ github.repository }}"
          };

          await script({ github, context, core }, scriptInputs);

