name: Output Scheduled Actions
description: ""

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      with:
        script: |
          const { owner, repo } = context.repo;

          const { data: variables } = await github.rest.actions.listRepoVariables({
            owner,
            repo
          });
          console.log('variables: ', variables)
