name: Output Scheduled Actions
description: ""

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      with:
        script: |
          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
          const ownerRepo = {
            owner: owner,
            repo: repo,
          };
          const variables = octokit.rest.actions.listRepoWorkflows(ownerRepo);
          console.log(variables);

