name: Output Scheduled Actions
description: ""

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  variables_json:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: run script
      shell: bash
      run: |
        num_schedules=$(echo '${{ inputs.variables_json }}' | jq 'keys | map(select(startswith("_SCHEDULE_")))')
        echo $num_schedules
