name: Workflow to test outputting variable relevant info

on:
  workflow_dispatch:

# permissions:
#   actions: read

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ./.github/actions/output-job-inputs
        with:
          variables_json: ${{ toJson(vars) }}
