name: test schedule wait

on:
  workflow_dispatch:
    inputs:
      wait-time:
        type: string
        description: "How long the workflow should wait (ms)"
        required: false
        default: "0" # Same default as austenstone/schedule
      wait-delay:
        type: string
        description: "How long between checks (ms)"
        required: false
        default: "20000" # Same default as austenstone/schedule

jobs:
  do-schedule:
    name: Schedule deployment
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment action scheduler token from github app
        id: github-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.SCHEDULE_APP_ID }}
          private-key: ${{ secrets.SCHEDULE_APP_KEY }}
          owner: ${{ github.repository_owner }}
      
      - uses: matthew-lewis20/schedule@general-improvments
        with:
          github-token: ${{ steps.github-app.outputs.token }}
          workflow: output-inputs.yml
          timezone: UTC
          # wait-ms: ${{ inputs.wait-time }} # Check for [inputted time]
          # wait-delay-ms: ${{ inputs.wait-delay }} # Wait [inputted time] between checks
