name: test echo vars

on:
  workflow_dispatch:

jobs:
  test-echo:
    name: Schedule deployment
    runs-on: ubuntu-latest
    steps:
      # Safety measure in case of issues
      - name: Dump vars
        run: echo ${{ toJson(vars) }}
